version: '3.8'

services:
  security-tracker:
    build: .
    ports:
      - "3001:3001"
    volumes:
      # Mount a volume for the SQLite database to persist data
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/items"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s